### PR TITLE
add higher level chunks to improve workflow

### PR DESCRIPTION
**Pull request by mmckegg**
slicer, synth, meddler

- [x] option from output/routing drop down to **Create Meddler**
- [x] make output/routing section consistent on all chunks
- [x] update routing when chunks renamed
- [x] Improve scroll to selected chunk so that it only does it when it should
- [x] Make it more obvious which chunk is selected (shadow?)
- [x] default shape [1,4]
- [x] duplicate chunks on grid
- [x] Show slices on slicer.

### CODE REVIEW

**Comment by mmckegg** [comment]
- [ ] option from output/routing drop down to **Create Meddler**
- [ ] make output/routing section consistent on all chunks
- [ ] update routing when chunks renamed
- [ ] make chunk area wider
- [ ] Improve scroll to selected chunk so that it only does it when it should
- [ ] Make it more obvious which chunk is selected (shadow?)
- [ ] link chunks together using shift+drag
- [ ] default shape [1,4]
- [ ] duplicate chunks on grid
- [ ] Apply default envelope to modulator chunk. Also an easy way to create ranges. 
- [ ] Show slices on slicer.

**Comment by mmckegg** [comment]
read to merge!!! :relaxed:

**Comment by ahdinosaur** [comment]
doo it ! :tada: :balloon: :birthday:

**Comment by ahdinosaur** [comment]
wow, this release brings Loop Drop to the next level, nice work @mmckegg :smiley_cat:

**Pull request merged**
